In [1]:
import torch

In [3]:
data = [
    [
        [1,2,3,4],
        [5,6,7,8,],
        [9,10,11,12,]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
]
t1 = torch.tensor(data)
print(f't1 = {t1}, type(t1) = {type(t1)}, t1.shape = {t1.shape}')

t1 = tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]), type(t1) = <class 'torch.Tensor'>, t1.shape = torch.Size([2, 3, 4])


In [4]:
y = len(t1)
print(f'y = {y}, type(y) = {type(y)}')
# 对于任意的张量x，len(x)返回的是第0维（最外层维度）上的大小

y = 2, type(y) = <class 'int'>


In [5]:
t1.sum(axis=1)
# A.sum(axis=1)会对张量沿着第一维进行求和操作，降维该维度
# 如t1的形状从(2,3,4)降维成了(2,4)

tensor([[15, 18, 21, 24],
        [51, 54, 57, 60]])

In [6]:
t1.sum(axis=0)
# (2,3,4)张量从0轴求和输出形状为(3,4)

tensor([[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]])

In [7]:
t1.sum(axis=2)
# (2,3,4)张量从2轴求和输出形状为(2,3)

tensor([[10, 26, 42],
        [58, 74, 90]])

In [12]:
t2 = t1.float()
norm_all = torch.linalg.norm(t2)
print(f"不指定 dim: {norm_all:.4f}")

不指定 dim: 70.0000


In [13]:
norm_dim0 = torch.linalg.norm(t2, dim=0)
norm_dim1 = torch.linalg.norm(t2, dim=1)
norm_dim2 = torch.linalg.norm(t2, dim=2)
print(f"dim=0 结果形状: {norm_dim0.shape}, dim=0结果: {norm_dim0}") 
print(f"dim=1 结果形状: {norm_dim1.shape}, dim=1结果: {norm_dim1}") 
print(f"dim=2 结果形状: {norm_dim2.shape}, dim=0结果: {norm_dim2}") 

dim=0 结果形状: torch.Size([3, 4]), dim=0结果: tensor([[13.0384, 14.1421, 15.2971, 16.4924],
        [17.7200, 18.9737, 20.2485, 21.5407],
        [22.8473, 24.1661, 25.4951, 26.8328]])
dim=1 结果形状: torch.Size([2, 4]), dim=1结果: tensor([[10.3441, 11.8322, 13.3791, 14.9666],
        [29.9833, 31.6860, 33.3916, 35.0999]])
dim=2 结果形状: torch.Size([2, 3]), dim=0结果: tensor([[ 5.4772, 13.1909, 21.1187],
        [29.0861, 37.0675, 45.0555]])


In [ ]:
# 如果linalg.norm函数中不指定dim，会将整个张量展平成一维数组，计算所有元素的范数
# 如果指定dim=x，则会沿着第x维计算范数，该维会被降维，最后输出的结果是原形状去掉第x维
# linalg.norm 的本质是对指定维度上的所有元素进行分组，对每组计算范数。组的划分由未指定的维度决定，输出形状就是这些未指定维度的形状